<a href="https://colab.research.google.com/github/robertosgpontes/tec_prog_1/blob/main/ExerciciosNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lista de Exercícios de Numpy

Deverá ser entrege até **11/02/2023** por meio do github que foi informado por vocês no [formulário](https://forms.office.com/r/YV12vEXGYF) respondido na aula de 01/02.

A entrega pela github é parte da avaliação.

## Questão 1

Crie um array 100 com valores aleatórios e ache os valores máximo e mínimo

In [2]:
import numpy as np

num_aleatorios = np.random.randint(1, 1000, 100)
print (num_aleatorios)

print("\n-------------------------------Informações------------------------------------")
print ('Valor Máximo: ' + str(max(num_aleatorios)))
print ('Valor Mínimo: ' + str(min(num_aleatorios)))

[535 826 344 826 484  71 960 805 396 160 401 697 732 420 810 741 812  53
 597 787 117 160 629 408 588 987 248  65 798 113 326 690 604 109 612 136
 308 504 452 812 345 542 152 888 337  87  24 518 589 570 748 886 439 763
 876 971 921 796  56 778 321  13 261  39 880 647 411 969 946 741  60   1
 234 845 404 312 121 901 353 246  55 744 531 892 419 465 754 424 787 120
 560 217 644 350 258 679 867 715 741 496]

-------------------------------Informações------------------------------------
Valor Máximo: 987
Valor Mínimo: 1


## Questão 2
Em Geometria Analítica, um **vetor** é uma quantidade que pode ser definida por um énuplo (uma sequência ordenada de *n* elementos) em que cada elemento representa a intensidade do vetor na direção especificada pela i-ésima componente desta sequência. 

Quando pensamos em duas dimensões, por exemplo, o vetor $R = (b,a)$ define, geometricamente, a entidade representada na figura abaixo, com componentes nos eixos x e y usuais.

<img src = "https://static.todamateria.com.br/upload/im/ag/image-721.jpg?auto_optimize=low" />

O **módulo** deste vetor, também chamado de intensidade, está geometricamente relacionado ao seu comprimento, e pode ser calculado diretamente pelas suas componentes, por meio de uma operação conhecida como **produto escalar** do vetor com ele mesmo. O módulo quadrático é expresso, desta forma, por:

$|A|^2 = \vec{A} \cdot \vec{A}$

Por outro lado, o produto escalar entre dois vetores $A = (a_{x}, a_{y})$ e $B = (b_{x}, b_{y})$ é dado por:

$\vec{A} \cdot \vec{B} = a_{x} \times b_{x} + a_{y} \times b_{y}$ (e esta definição vale para qualquer que seja a dimensão do vetor).

O módulo quadrático de um vetor é, portanto:

$|A|² = a_{x}^2 + b_{x}^2$.

Dado o exposto acima, escreva uma função que retorne o módulo de um vetor n-dimensional qualquer.

In [17]:
def modulo(x):
    soma = 0
    for i in x:
        soma+=(i*i)

    modulo = (soma)**(0.5)
    return modulo

x = np.array ([2,2,2])
print("|A| = ",modulo(x))

|A| =  3.4641016151377544


## Questão 3

Em uma **análise de regressão**, usualmente estamos interessados em descrever relações entre variáveis de um dado conjunto de dados por meio de uma **função** que descreva, o tanto quanto possível, estas relações.

Por exemplo, no gráfico abaixo, os pontos vermelhos relacionam as medidas das duas variáveis sendo avaliadas (nos eixos x e y); e a linha azul aproxima a relação entre elas por uma função linear.

![Normdist_regression.png](https://miro.medium.com/v2/resize:fit:786/format:webp/1*LEmBCYAttxS6uI6rEyPLMQ.png)

É possível ver que nem todos os pontos obedecem exatamente à relação ditada pela reta (isto é, há pontos que não estão exatamente "sobre a reta"; mas, sim, ligeraimente acima, ou abaixo, dela). Isto, contudo, é esperado em um modelo de regressão, por inúmeras fontes de incerteza associadas às medições.

Uma das métricas que utilizamos para avaliar a qualidade de uma regressão é o **erro quadrático médio (EQM)**, que mensura a diferença total entre cada predição da regressão ($y_{prediction}$; que no nosso caso seriam os valores de y para a reta azul) com o valor real de cada i-ésima medida ($y_{i}$; que no nosso caso seriam as coordenadas y para cada ponto vermelho do gráfico). O EQM pode ser definido como:

$EQM = \frac{1}{n}\sum_{i=1}^{n}(y_{prediction} - y_{i})^2$.

Isto posto, escreva uma função que calcule o EQM recebendo, como entrada, os vetores $y_{prediction}$ e $y_{i}$. Por exemplo, digamos que sua função se chame *calculate_eqm*, ela deve operar da seguinte forma:

In [4]:
import math  
import numpy as np  
 
def calculate_eqm(y_prediction,y_i):
    res = np.square(np.subtract(y_prediction,y_i)).mean()   
    eqm = math.sqrt(res) 
    return eqm

y_i = [1,2,3]
y_prediction = [0,0,3]

print("EQM: {}".format(str(calculate_eqm(y_prediction,y_i)))) 

EQM: 1.2909944487358056


## Questão 4

Crie um array 2D (bidimensional) com 1 na borda e 0 dentro

In [4]:
def matriz_1(a,b):
    
    mat= np.zeros((a,b))
    mat[0,:]= 1 
    mat[-1,:]= 1  
    mat[:,0]= 1  
    mat[:,-1]= 1 
    return mat

matriz_1(5,5)

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

## Questão 5

Como adicionar uma borda de 0's ao redor de um array 2D (bidimensional) existente

In [6]:
def matriz_2(mat):

    mat = np.pad (mat, pad_width=1, mode='constant', constant_values=0)
    return mat

mat = np.ones((5,5))
matriz_2(mat)

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

## Questão 6

 A eletroencefalografia (EEG) é uma técnica que mensura potenciais elétricos cerebrais em diversas regiões do escalpo do paciente. Suponha que você recebeu um conjunto de dados na forma de uma matriz de 64 x 512 elementos, em que cada linha contém o sinal gravado em um dos **eletrodos** espalhados pelo escalpo em um exame de EEG, e cada coluna contém um valor de potencial elétrico, em microvolts. 

Como o sinal de EEG é muito suscetível a ruídos externos (interferências na qualidade do sinal), uma operação comum para atenuar a interferência no sinal consiste em tirar a média do potencial elétrico de todos os eletrodos, e subtrair este valor de cada um deles. Isto atenua fontes de ruído ao sinal comuns a todos os eletrodos. Em termos matemáticos, o sinal processado por esta operação, $X_{e,i}$ para cada eletrodo (e) e amostra (i), é dado por:

$X_{e,i} = \hat{X_{e,i}} - \frac{1}{N}\sum_{e=1}^{N}\hat{X_{e,i}}$,

em que $\hat{X_{e,i}}$ representa o sinal original (ou seja, é a matriz de entrada de 64 x 512 elementos), e $N$ indica o total de eletrodos.

Com o exposto acima, escreva uma função que retorne uma matriz com os sinais de EEG processados conforme a operação mencionada. Sua função deve operar conforme o exemplo abaixo.

In [18]:
def process_EEG_signal (sinal):

    media = sinal.mean()
    subt = media/(sinal.size)
    result = sinal - subt

    return result

sinal = np.random.randn(64,512)

print("---------------------------Matriz com Sinais EEG-----------------------------------")
print("\n", process_EEG_signal(sinal))

---------------------------Matriz com Sinais EEG-----------------------------------

 [[ 0.00995597 -0.51114905 -0.46721246 ... -1.48368073  0.87029018
   0.35986819]
 [ 0.65722129 -0.39130339  1.29089913 ...  0.2410644  -1.64113666
  -0.54258623]
 [ 1.39981439  0.13215388  0.44799617 ...  0.29292618 -0.25970924
   1.27148167]
 ...
 [-0.5567833  -0.18873658  1.26771274 ... -0.88579707 -0.3308949
  -1.90131795]
 [ 1.81907645 -1.25212899 -0.8161035  ... -1.20948202 -0.26142529
  -1.28560197]
 [-1.10176721 -1.03713093 -1.97251377 ... -0.90401072 -0.93779198
   0.70755965]]


## Questão 7

Em estatística, um **outlier** é um valor que destoa consideravelmente da distribuição à qual está associado. Um dos critérios para idenficar outliers consiste em encontrar a **distância interquantil** (IQR), ou seja, a diferença entre o terceiro (Q3) e o primeiro quartis (Q1) da distribuição, e tomar como outliers todos os pontos abaixo do Limite Inferior (LI = Q1 - 1.5*IQR  ), ou acima do Limite Superior (LS = Q3 + 1.5*IQR).

![image.png](https://s3-sa-east-1.amazonaws.com/lcpi/0d8a7b04-b982-4e6b-9fc7-fbb062247d8d.png)


<img src = "https://blog.curso-r.com/images/posts/banner/outlier.webp" />

Escreva uma função que, dada uma matriz de dados de entrada de dimensões $N_{observações} \times N_{features}$ retorne três requisitos: 
- uma matriz booleana indicando a existência de outliers nos dados de entrada;
- a quantidade de outliers
- quem são os outliers (os valores).

**Algumas definições:**
- um *quantil* divide a distribuição, após ordenados os pontos, segundo algum ponto de corte;
- o **primeiro quartil** é o ponto para o qual 25 % dos valores da distribuição estão abaixo dele;
- o **terceiro quartil** é o ponto para o qual 75 % dos valores da distribuição estão abaixo dele.

Pode ser útil consultar a função **numpy.quantile**.

Exemplo de operação da função:

In [19]:
def locate_outliers(X): 
    import numpy as np
    q1 = np.quantile(X,.25, axis=0)
    q3 = np.quantile(X,.75, axis=0)
    iqr = (q3 - q1)
    is_outlier = ((X < (q1 - iqr.dot(1.5)))) | (X > (q3 + iqr.dot(1.5)))
    outliers_count = (X[is_outlier]).size
    outliers = X[is_outlier]
    return (is_outlier, outliers_count, outliers)

X = np.random.randn(1000,15)

is_outlier, outliers_count, outliers = locate_outliers(X)
print("---------------------------Matriz booleana-----------------------------------")
print("\n", is_outlier)
print("\n---------------------------------------------------------------------------")
print("\n --> Contagem de outliers: ", outliers_count)
print("\n-------------------------------Outliers------------------------------------")
print("\n", outliers)

---------------------------Matriz booleana-----------------------------------

 [[False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [False False False ... False False False]
 [False  True False ... False False False]
 [False False False ... False False False]]

---------------------------------------------------------------------------

 --> Contagem de outliers:  131

-------------------------------Outliers------------------------------------

 [-2.69766415 -2.71964021 -2.69070501  2.91433569  2.77757704 -3.03246428
  3.28060563  2.71337263 -2.72147658  2.66344998 -2.75945747  3.02087473
  4.12274769 -2.91121596  2.74657651 -3.02353194 -2.76240186 -2.81637056
  2.7556974   2.62831123 -3.27740742 -3.42869832 -2.93380911  2.74229486
 -3.64579364  2.83253474  3.28221759 -2.68118728 -2.83791789 -3.21544674
  2.65894874  3.31169275 -2.87301313 -3.07043753  2.94005015 -2.88756017
 -3.12030649  3.62780525 -2.7

## Questão 8

Crie um vetor com valores que vão de 1 até 21 de dois em dois, a partir da função arange

In [20]:
x = np.arange(1, 21, 2)
print("\n-------------------------------Valores Aleatórios------------------------------------")
x


-------------------------------Valores Aleatórios------------------------------------


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

## Questão 9

Crie um array de 10 com valores aleatórios

In [21]:
ale = np.random.randint(1,1000,10)
print("\n-------------------------------Valores Aleatórios------------------------------------")
ale


-------------------------------Valores Aleatórios------------------------------------


array([762, 318, 904, 924, 701, 333, 287, 299, 379, 960])

## Questão 10

Em estatística, a normalização de uma distribuição de dados pode ser feita subtraindo o valor médio da distribuição de cada valor do conjunto de dados, dividindo o resultado pelo desvio-padrão da distribuição. Escreva uma função que normalize os dados recebidos por um array numpy qualquer, conforme descrito anteriormente.

In [22]:
def normalize(X):
    desvio = X.std()
    media =  X.mean()
    normalizado = (X-media).dot(1/desvio)
    return normalizado
print("-------------------------------Distribuição Normalizada------------------------------------")
print("\n", normalize(ale))

-------------------------------Distribuição Normalizada------------------------------------

 [ 0.64015115 -0.98122426  1.15869914  1.23173406  0.41739461 -0.92644806
 -1.0944284  -1.05060744 -0.75846773  1.36319693]


## Questão 11

Escreva uma função em numpy que receba um array contendo notas de uma turma de 100 estudantes. Considere que a nota de aprovação da turma é 5.0. A função deve retornar, em um array numpy, nesta ordem:
- a média e o desvio-padrão das notas da turma;
- o número de notas maiores que 7.0;
- o número de reprovações da turma;
- a menor nota da turma;
- a maior nota da turma.

In [23]:
def info_notas(notas):
    notas = np.random.randint(0, 10, 100)
    print (notas)
    media = notas.mean()
    desvio_padrao = notas.std()
    count_aprovados = 0
    count_reprovados = 0
    for i in notas:
        if notas[i] >= 5:
            count_aprovados +=1
        else:
            count_reprovados +=1
    menor_nota = notas.min()
    maior_nota = notas.max()
    return media, desvio_padrao, count_aprovados, count_reprovados, menor_nota, maior_nota 

notas = np.random.randint(0, 10, 100)
info = info_notas(notas)

print("\n-------------------------------Informações------------------------------------")
print("Média: " + str(info[0]))
print("Desvio Padrão: " + str(info[1]))
print("Quantidade Aprovados: " + str(info[2]))
print("Quantidade Reprovados: " + str(info[3]))
print("Menor Nota: " + str(info[4]))
print("Maior Nota: " + str(info[5]))

[8 7 0 0 3 2 1 6 8 0 8 1 4 0 4 8 6 6 8 2 7 0 8 9 2 1 0 6 7 6 0 7 1 1 1 3 1
 3 3 7 7 4 7 6 8 7 0 2 9 5 4 6 3 4 8 3 0 6 0 9 3 2 1 8 4 9 7 2 7 1 9 4 0 6
 1 6 6 4 0 8 9 6 5 4 5 2 8 2 8 0 2 8 9 3 9 8 8 3 4 3]

-------------------------------Informações------------------------------------
Média: 4.47
Desvio Padrão: 3.0048460859085613
Quantidade Aprovados: 48
Quantidade Reprovados: 52
Menor Nota: 0
Maior Nota: 9


In [ ]:
#Fim